version : 0.0
os : linux
files:
  - source: /
    destination: /home/ubuntu/musinsa-watcher/backend/deploy/zip
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu